
version: 2

sources:
  - name: raw_postgres_data  
    schema: public
    tables:
      - name: orders 
      - name: customers
models:
  - name: contact_list
    description: "The list of emails to contact"
    columns:
      - name: phone
        description: "The phone number of the customer"
        tests:
          - not_null
