version: "3.5"
services:
  mypostgres:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgresPass"
      POSTGRES_DB: "testme"
    ports:
      - "5432:5432"

  kensu_load_data_with_pandas_v1:
    image: kensuio/kensu-dbt-postgres:dev2.0
    environment:
      KSU_CONF_FILE: "/kensu-dbt-example/conf.custom.ini"
    volumes:
      - ./pandas-load-data:/pandas-load-data
      - ./conf.default.ini:/kensu-dbt-example/conf.custom.ini
    working_dir: /pandas-load-data/
    entrypoint: ["/root/pandas-load-data-script/pandas-venv/bin/python3","/pandas-load-data/load_campain.py", "first"]
    depends_on:
      - mypostgres

  kensu_load_data_with_pandas_v2:
    image: kensuio/kensu-dbt-postgres:dev2.0
    environment:
      KSU_CONF_FILE: "/kensu-dbt-example/conf.custom.ini"
    volumes:
      - ./pandas-load-data:/pandas-load-data
      - ./conf.default.ini:/kensu-dbt-example/conf.custom.ini
    working_dir: /pandas-load-data/
    entrypoint: ["/root/pandas-load-data-script/pandas-venv/bin/python3", "/pandas-load-data/load_campain.py", "second"]
    depends_on:
      - mypostgres

  kensu_run_dbt_postgres:
    image: kensuio/kensu-dbt-postgres:dev2.0
    environment:
      KSU_CONF_FILE: "/kensu-dbt-example/conf.custom.ini"
      DBT_CURRENT_PROJECT_DIR: "/kensu-dbt-example/dbt-projects/example_marketing"
    volumes:
      # - ./sql-parser.log:/kensu-dbt-example/sql-parser.log
      - ./profile_marketing.yml:/.dbt/profiles.yml
      - ./example_marketing:/kensu-dbt-example/dbt-projects/example_marketing
      - ./conf.default.ini:/kensu-dbt-example/conf.custom.ini
    depends_on:
      - mypostgres
